{% set version = "1.14.7-1" %}
{% set sha256 = "13ad3af364705f97b8d872dc3de8f12930ef448ac6119f527f36bbed82925e2c" %}
{% set version = "1.14.7-1" %}
{% set sha256 = "13ad3af364705f97b8d872dc3de8f12930ef448ac6119f527f36bbed82925e2c" %}

package:
  name: ros-rosboost-cfg
  version: {{ version.split("-")[0] }}

source:
  url: https://github.com/ros-gbp/ros-release/archive/release/melodic/rosboost_cfg/{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  number: 0  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make  # [unix]
  host:
    - ros-conda-mutex * melodic
    - ros-conda-base
    - python
    - catkin_pkg
    - ros-catkin
  run:
    - ros-conda-mutex * melodic
    - ros-conda-base
    - python

test:
  requires:
    - rospkg
  commands:
    - export ROS_ROOT=$PREFIX && python -c "import rospkg;s = rospkg.RosPack();ret = s.get_path('rosboost_cfg');print(ret)"

about:
  home: http://ros.org/wiki/rosboost_cfg
  summary: |
    Contains scripts used by the rosboost-cfg tool for determining cflags/lflags/etc. of boost on your system
  description: |
    Contains scripts used by the rosboost-cfg tool for determining
    cflags/lflags/etc. of boost on your system
  license: BSD-3-Clause
  license_file: src/rosboost_cfg/__init__.py

extra:
  recipe-maintainers:
    - wolfv
    - lesteve
    - seanyen
